version: '3.6'

volumes:
  postgres_data:

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: Cms
      POSTGRES_USER: Cms
      POSTGRES_PASSWORD: Cms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
